CROP_KNOWLEDGE = [
    # Rice
    {"id": "rice_001", "content": "Rice (paddy) is a Kharif crop sown June-July and harvested October-December. Requires 25°C-35°C temperature and 100-150cm annual rainfall. Clay loam soil with pH 5.5-6.5 is ideal.", "tags": ["rice", "sowing", "soil", "climate"]},
    {"id": "rice_002", "content": "Rice blast is a major fungal disease causing diamond-shaped lesions on leaves. Control with tricyclazole 0.1% spray or carbendazim 0.1% at first sign. Use resistant varieties like IR-64, Pusa Basmati.", "tags": ["rice", "disease", "fungal", "blast", "control"]},
    {"id": "rice_003", "content": "Brown plant hopper (BPH) is a serious rice pest causing 'hopper burn'. Use neem oil 2% or imidacloprid 0.05% spray. Maintain 2-5cm water depth and avoid excess nitrogen.", "tags": ["rice", "pest", "bph", "insect", "control"]},
    {"id": "rice_004", "content": "Rice requires 120-150kg nitrogen per hectare. Apply 50% N as basal, 25% at tillering, 25% at panicle initiation. Use DAP 60kg/ha and MOP 40kg/ha for phosphorus and potassium.", "tags": ["rice", "fertilizer", "nitrogen", "nutrition"]},
    {"id": "rice_005", "content": "Rice blast (Pyricularia oryzae): Diamond-shaped lesions with gray centers on leaves, nodes, and panicles. Severe in high humidity >90% and temperatures 25-28°C. Prevent with seed treatment (tricyclazole 2g/kg seed).", "tags": ["rice", "disease", "blast", "symptoms", "prevention"]},
    {"id": "rice_006", "content": "Bacterial leaf blight (Xanthomonas oryzae) causes yellow-to-white wavy lesions along leaf veins. Seedling wilting and yield loss up to 60%. Spray streptocycline 200ppm + copper oxychloride 0.3%.", "tags": ["rice", "disease", "bacterial", "blight", "control"]},
    {"id": "rice_007", "content": "Sheath blight (Rhizoctonia solani): Oval-to-irregular green-gray lesions on leaf sheaths. Prevalent in dense canopy with high humidity. Apply validamycin 3L/ha or propiconazole 0.1% at boot leaf stage.", "tags": ["rice", "disease", "sheath blight", "fungal", "control"]},
    {"id": "rice_008", "content": "Rice stem borer: Dead heart in vegetative stage, white earhead in reproductive stage. Use carbofuran 3G granules 33kg/ha at 15-20 days after transplanting. Install pheromone traps at 12/ha.", "tags": ["rice", "pest", "stem borer", "insect", "management"]},

    # Wheat
    {"id": "wheat_001", "content": "Wheat is a Rabi crop sown October-December and harvested March-April. Optimal temperature 15°C-25°C with cool winters. Well-drained loam soil pH 6.0-7.5 is ideal.", "tags": ["wheat", "sowing", "soil", "climate"]},
    {"id": "wheat_002", "content": "Wheat rust (yellow/brown/black): Yellow rust shows yellow stripes on leaves, brown rust has circular brown pustules, black rust appears on stems. Control with propiconazole 0.1% or tebuconazole 0.1%. Resistant varieties: HD-2967, PBW-343.", "tags": ["wheat", "disease", "rust", "fungal", "control"]},
    {"id": "wheat_003", "content": "Wheat requires 120-150kg N, 60kg P2O5, 40kg K2O per hectare. Apply full P&K + half N as basal, remaining N at crown root initiation (21 DAS) and tillering (45 DAS).", "tags": ["wheat", "fertilizer", "nitrogen", "nutrition"]},
    {"id": "wheat_004", "content": "Wheat aphid: Colonies on leaves, stems, and ears causing stunted growth. Spray dimethoate 0.05% or imidacloprid 0.05% when threshold of 5-10 aphids per tiller is crossed. Conserve natural enemies like ladybird beetles.", "tags": ["wheat", "pest", "aphid", "insect", "control"]},
    {"id": "wheat_005", "content": "Loose smut of wheat replaces grain heads with black powdery mass of spores. Treat seeds with carboxin 0.2% or vitavax 2.5g/kg seed. Use certified disease-free seed.", "tags": ["wheat", "disease", "smut", "seed treatment", "prevention"]},
    {"id": "wheat_006", "content": "Wheat requires 4-6 irrigations: crown root initiation (21 DAS), tillering (45 DAS), jointing (60 DAS), flowering (80 DAS), milking (95 DAS), and grain filling (110 DAS). Critical stages: crown root initiation and flowering.", "tags": ["wheat", "irrigation", "water", "critical stages"]},

    # Maize
    {"id": "maize_001", "content": "Maize is grown in both Kharif and Rabi seasons. Requires 20°C-30°C temperature and 50-100cm rainfall. Well-drained sandy loam with pH 5.5-7.0.", "tags": ["maize", "sowing", "climate", "soil"]},
    {"id": "maize_002", "content": "Fall armyworm (Spodoptera frugiperda) is a major maize pest. Young larvae feed on whorl leaves causing window-pane damage. Spray emamectin benzoate 0.4g/L or spinetoram 0.5ml/L. Apply neem cake 250kg/ha at sowing.", "tags": ["maize", "pest", "fall armyworm", "control", "insect"]},
    {"id": "maize_003", "content": "Maize requires 150-200kg N, 60-80kg P2O5, 60-80kg K2O per hectare. Apply 1/3 N + full P&K at sowing, 1/3 N at knee-high stage (30 DAS), 1/3 N at tasseling (55 DAS). Zinc deficiency causes white bud — apply ZnSO4 25kg/ha.", "tags": ["maize", "fertilizer", "nutrition", "zinc"]},
    {"id": "maize_004", "content": "Turcicum leaf blight of maize: Elliptical gray-green lesions that coalesce causing leaf drying. Manage with mancozeb 0.25% spray at first appearance. Grow resistant hybrids like PMH-1.", "tags": ["maize", "disease", "leaf blight", "fungal", "control"]},
    {"id": "maize_005", "content": "Maize stem borer (Chilo partellus): Dead heart symptom in young plants. Apply carbofuran 3G granules 8kg/ha in whorl at 15-20 DAS. Use trichogramma cards at 50,000/ha for biological control.", "tags": ["maize", "pest", "stem borer", "biological control"]},

    # Sugarcane
    {"id": "sugarcane_001", "content": "Sugarcane is planted October-February (spring) and September-October (autumn). Requires 25°C-35°C and 100-175cm rainfall. Deep well-drained loam with pH 6.5-7.5.", "tags": ["sugarcane", "sowing", "climate", "soil"]},
    {"id": "sugarcane_002", "content": "Red rot (Colletotrichum falcatum): Most destructive sugarcane disease. Causes reddened internal tissue with white patches crosswise. Use disease-free setts, treat with carbendazim 0.1% for 10 minutes. Resistant varieties: Co-0238, Co-05011.", "tags": ["sugarcane", "disease", "red rot", "fungal", "management"]},
    {"id": "sugarcane_003", "content": "Sugarcane requires 250-300kg N, 60-80kg P2O5, 60-80kg K2O per hectare. Apply full P&K + 50% N at planting, 25% N at tillering (60 DAP), 25% N at grand growth (120 DAP).", "tags": ["sugarcane", "fertilizer", "nutrition"]},
    {"id": "sugarcane_004", "content": "Sugarcane early shoot borer causes dead hearts 30-50 days after planting. Apply carbofuran 3G 33kg/ha in soil at planting time. Remove and destroy dead hearts.", "tags": ["sugarcane", "pest", "shoot borer", "control"]},

    # Cotton
    {"id": "cotton_001", "content": "Cotton is a Kharif crop sown April-June. Requires 20°C-35°C and 60-100cm rainfall. Black cotton soil (regur) with pH 6.0-8.0 is ideal.", "tags": ["cotton", "sowing", "climate", "soil"]},
    {"id": "cotton_002", "content": "Pink bollworm (Pectinophora gossypiella): Most destructive cotton pest. Larvae bore into bolls, feed on seeds, causing rosette flowers. Use Bt cotton, install pheromone traps 5/ha, spray neem oil 5% at flowering.", "tags": ["cotton", "pest", "pink bollworm", "bt", "control"]},
    {"id": "cotton_003", "content": "Cotton requires 100-120kg N, 50-60kg P2O5, 50-60kg K2O per hectare. Apply 50% N + full P&K at sowing, 25% N at square formation (40 DAS), 25% N at flowering (70 DAS).", "tags": ["cotton", "fertilizer", "nutrition"]},
    {"id": "cotton_004", "content": "Cotton leaf curl virus: Upward curling of leaves with vein thickening. Transmitted by whitefly. Control whitefly with imidacloprid 0.05% and remove infected plants. Resistant varieties: Anjali, Vikram.", "tags": ["cotton", "disease", "leaf curl", "virus", "whitefly"]},
    {"id": "cotton_005", "content": "American bollworm (Helicoverpa armigera): Feeds on squares, flowers, and bolls causing heavy shedding. Spray emamectin benzoate 1g/10L or indoxacarb 1ml/L at egg stage. Bt cotton provides effective control.", "tags": ["cotton", "pest", "bollworm", "helicoverpa", "control"]},

    # Groundnut
    {"id": "groundnut_001", "content": "Groundnut is a Kharif crop. Requires 25°C-30°C and 50-75cm rainfall. Well-drained sandy loam with pH 6.0-7.0. Cannot tolerate waterlogging.", "tags": ["groundnut", "sowing", "climate", "soil"]},
    {"id": "groundnut_002", "content": "Tikka disease (Cercospora leaf spot): Circular brown spots with yellow halo on leaves causing defoliation. Spray mancozeb 0.2% or chlorothalonil 0.2% at 15-day intervals starting 30 DAS.", "tags": ["groundnut", "disease", "tikka", "leaf spot", "control"]},
    {"id": "groundnut_003", "content": "Groundnut requires 20-25kg N, 40-60kg P2O5, 50-70kg K2O per hectare. Apply full dose as basal. Also apply gypsum 500kg/ha at pegging stage for pod development.", "tags": ["groundnut", "fertilizer", "gypsum", "nutrition"]},
    {"id": "groundnut_004", "content": "Groundnut stem rot (Sclerotium rolfsii): White mycelial growth on stems near soil line, wilting, and pod rot. Avoid excessive moisture, practice crop rotation with cereals, apply Trichoderma viride 2.5kg/ha in soil.", "tags": ["groundnut", "disease", "stem rot", "biological control"]},

    # General pest management
    {"id": "general_pest_001", "content": "Integrated Pest Management (IPM): Combine biological, cultural, mechanical, and chemical methods. Use resistant varieties, conserve natural enemies, practice crop rotation, monitor with pheromone traps, spray only at economic threshold levels.", "tags": ["general", "pest", "ipm", "integrated", "management"]},
    {"id": "general_pest_002", "content": "Biological control agents: Trichogramma (egg parasitoid) for lepidopteran pests, Chrysoperla (green lacewing) for aphids, Neem-based products for general pests. Pseudomonas fluorescens for soil-borne disease suppression.", "tags": ["general", "biological control", "predators", "parasitoids"]},
    {"id": "general_pest_003", "content": "Natural enemies of crop pests: Ladybird beetles (aphids), Chrysoperla (aphids, eggs), spiders (general predators), Trichogramma (egg parasitoid), Braconid wasps (caterpillars). Conserve through reduced pesticide use and flowering hedges.", "tags": ["general", "natural enemies", "beneficial insects", "conservation"]},

    # Soil management
    {"id": "soil_001", "content": "Soil testing every 2-3 years is essential. Collect samples from 15cm depth at 10 locations per acre, mix thoroughly, and submit 500g to soil testing lab. Test for pH, EC, organic carbon, N, P, K, S, Zn, Fe, Mn, Cu, B.", "tags": ["soil", "testing", "sampling", "nutrients"]},
    {"id": "soil_002", "content": "Organic matter management: Apply well-decomposed FYM 10-15 tons/ha or vermicompost 5 tons/ha annually. Green manuring with dhaincha or sunn hemp adds 50-80kg N/ha. Incorporate crop residues after harvest.", "tags": ["soil", "organic matter", "fym", "vermicompost", "green manure"]},
    {"id": "soil_003", "content": "Soil pH management: Acidic soil (pH <5.5) requires liming — apply 2-4 tons/ha lime. Alkaline soil (pH >8.5) needs gypsum 5-10 tons/ha plus organic matter. Most crops prefer pH 6.0-7.5 for optimal nutrient availability.", "tags": ["soil", "pH", "lime", "gypsum", "amendment"]},
    {"id": "soil_004", "content": "Micronutrient deficiencies: Zn — white/yellow interveinal chlorosis (apply ZnSO4 25kg/ha); Fe — interveinal chlorosis on young leaves (FeSO4 spray 0.5%); B — hollow stems, poor fruit set (borax 10kg/ha); Mn — gray specks on leaves (MnSO4 0.5% spray).", "tags": ["soil", "micronutrient", "deficiency", "zinc", "iron", "boron"]},
    {"id": "soil_005", "content": "Crop rotation principles: Rotate deep-rooted with shallow-rooted crops, legumes with non-legumes, cereals with pulses. Avoid growing same crop family in consecutive seasons to break pest and disease cycles.", "tags": ["soil", "crop rotation", "principles", "management"]},

    # Water management
    {"id": "water_001", "content": "Drip irrigation saves 40-60% water compared to flood irrigation. Ideal for row crops like sugarcane, vegetables, cotton. Combine with fertigation for 25% higher fertilizer use efficiency. Install filter and pressure regulator.", "tags": ["water", "drip", "irrigation", "fertigation", "efficiency"]},
    {"id": "water_002", "content": "Sprinkler irrigation suitable for closely spaced crops like wheat, pulses, vegetables. Saves 30-40% water. Wind speed >15 km/h reduces uniformity. Best for sandy soils with high infiltration rate.", "tags": ["water", "sprinkler", "irrigation", "efficiency"]},
    {"id": "water_003", "content": "Critical crop growth stages for irrigation: Rice — panicle initiation and flowering; Wheat — crown root initiation and flowering; Maize — tasseling and grain filling; Sugarcane — tillering and grand growth; Cotton — flowering and boll development.", "tags": ["water", "irrigation", "critical stages", "crop"]},
    {"id": "water_004", "content": "Rainwater harvesting: Construct farm ponds (1% of farm area for every 100mm rainfall). Use lined ponds in high-permeability soils. Store water for protective irrigation during dry spells. Check dam construction in watershed.", "tags": ["water", "rainwater", "harvesting", "pond", "conservation"]},

    # Weather-based advisories
    {"id": "weather_001", "content": "Heat wave (temp > 40°C): Increase irrigation frequency, apply mulch to conserve soil moisture, provide shade nets for vegetables, spray anti-transpirants. Avoid fertilizer application during heat stress.", "tags": ["weather", "heat", "stress", "management", "irrigation"]},
    {"id": "weather_002", "content": "Heavy rain (>50mm in 24h): Ensure drainage in fields, avoid fertilizer/pesticide application, stake tall plants, harvest mature fruits/vegetables. After rain: drain excess water, check for pest outbreak, apply fungicide if needed.", "tags": ["weather", "rain", "flood", "drainage", "management"]},
    {"id": "weather_003", "content": "Cold wave/frost (temp < 5°C): Irrigate fields before frost night (water releases heat), cover seedlings with polythene/protective covers, spray 0.1% sulfur to protect blossoms. Grow windbreaks on field boundaries.", "tags": ["weather", "cold", "frost", "protection", "management"]},
    {"id": "weather_004", "content": "Drought conditions: Use drought-tolerant varieties, apply mulch 5-10cm thick, practice skip-irrigation, use anti-transpirants like kaolin spray 3%. Postpone transplanting until conditions improve. Foliar spray of 2% urea for stress tolerance.", "tags": ["weather", "drought", "management", "mulch", "conservation"]},
    {"id": "weather_005", "content": "High humidity (>85%): Monitor for fungal disease outbreaks (blight, mildew, rot). Apply preventive fungicide sprays, improve air circulation through proper spacing, avoid overhead irrigation. Delay nitrogen application.", "tags": ["weather", "humidity", "fungal", "disease", "prevention"]},
    {"id": "weather_006", "content": "Wind speed > 20 km/h: Delay spraying operations (drift loss), stake tall crops, check windbreak effectiveness. For fruit orchards, ensure proper staking. Hail nets recommended in hail-prone areas.", "tags": ["weather", "wind", "spray", "protection"]},

    # Fertilizer management
    {"id": "fert_001", "content": "Neem-coated urea (NCU): 15-20% more efficient than prilled urea. Reduces nitrogen loss through leaching and denitrification. Apply NCU 10-12 days before crop requirement stage. Available as 46% N.", "tags": ["fertilizer", "urea", "neem-coated", "efficiency"]},
    {"id": "fert_002", "content": "Bio-fertilizers: Rhizobium (pulses — 200g/10kg seed), Azospirillum (cereals — 5kg/ha), PSB (phosphate solubilizing — 5kg/ha), Azolla (rice — 0.5-1 ton/ha as green manure). Apply near root zone within 24h of mixing.", "tags": ["fertilizer", "biofertilizer", "rhizobium", "azospirillum", "psb"]},
    {"id": "fert_003", "content": "Vermicompost: 1.5-2.5% N, 0.5-1.5% P2O5, 0.5-1.5% K2O. Apply 5 tons/ha. Earthworms (Eisenia fetida) process 1 ton organic waste in 30-45 days. Keep bedding moist (40-50%) and shaded.", "tags": ["fertilizer", "vermicompost", "organic", "earthworms"]},
    {"id": "fert_004", "content": "Fertigation schedule: Inject water-soluble fertilizers through drip system. Common schedule — 1/4 dose at seedling, 1/2 at vegetative growth, 1/4 at reproductive stage. Use 19:19:19 NPK for vegetative stage, 12:61:00 for flowering.", "tags": ["fertilizer", "fertigation", "drip", "schedule"]},
    {"id": "fert_005", "content": "Leaf color chart (LCC) for nitrogen management in rice: Hold LCC on fully expanded top leaf. If color <4, apply 30kg N/ha. If >4, skip. Use every 7-10 days from 14 DAT to flowering. Saves 25-30% N without yield loss.", "tags": ["fertilizer", "nitrogen", "lcc", "rice", "management"]},

    # Vegetables
    {"id": "veg_001", "content": "Tomato: Temperature 20°C-27°C, pH 6.0-6.8. Common diseases: early blight (mancozeb 0.2%), late blight (metalaxyl 0.2%), leaf curl virus (control whitefly with imidacloprid). Stake plants for better fruit quality.", "tags": ["tomato", "vegetable", "disease", "temperature", "management"]},
    {"id": "veg_002", "content": "Brinjal/eggplant: Temperature 22°C-30°C. Shoot and fruit borer is major pest — remove infected shoots, spray emamectin benzoate 1g/10L, use pheromone traps. Practice crop rotation with non-solanaceous crops.", "tags": ["brinjal", "eggplant", "pest", "borer", "management"]},
    {"id": "veg_003", "content": "Chilli: Temperature 20°C-30°C. Major pests: thrips, mites, fruit borer. Diseases: anthracnose (mancozeb + carbendazim), leaf curl (imidacloprid for vector control). Apply FYM 25t/ha + 100:50:50 NPK kg/ha.", "tags": ["chilli", "pepper", "pest", "disease", "management"]},
    {"id": "veg_004", "content": "Onion: Temperature 15°C-25°C (bulbing requires long days). Major pest: thrips (spray dimethoate 0.05%). Diseases: purple blotch (mancozeb 0.2%), downy mildew (metalaxyl 0.2%). Reduce irrigation 15 days before harvest.", "tags": ["onion", "vegetable", "pest", "disease", "management"]},
    {"id": "veg_005", "content": "Okra/ladyfinger: Temperature 25°C-35°C. Yellow vein mosaic virus management: control whitefly vector, remove infected plants, use resistant varieties (Pusa Sawani, Varsha Uphar). Fruit borer: spray cypermethrin 0.05%.", "tags": ["okra", "ladyfinger", "virus", "pest", "management"]},

    # Fruits
    {"id": "fruit_001", "content": "Mango: Temperature 25°C-35°C, pH 5.5-7.5. Major diseases: powdery mildew (dinocap 0.1%), anthracnose (carbendazim 0.1%), mango malformation (deblossoming + NAA spray). Apply FYM 50kg/tree + 1:0.5:1 kg NPK/tree/year.", "tags": ["mango", "fruit", "disease", "management"]},
    {"id": "fruit_002", "content": "Banana: Temperature 25°C-35°C, pH 6.0-7.5. Panama wilt (Fusarium): Use disease-free tissue culture plants, soil drench with carbendazim 0.1%. Sigatoka leaf spot: spray mancozeb 0.2% + tridemorph 0.1%. Apply 300g N + 100g P + 300g K per plant.", "tags": ["banana", "fruit", "disease", "wilt", "management"]},
    {"id": "fruit_003", "content": "Citrus (lemon, orange): Temperature 20°C-35°C. Major disease: citrus canker (bacterial) — spray streptocycline 100ppm + copper oxychloride 0.3%. Major pest: citrus leaf miner (spray imidacloprid 0.05%). Nutrition: 600g N + 200g P + 300g K per tree annually.", "tags": ["citrus", "lemon", "orange", "disease", "pest", "management"]},
    {"id": "fruit_004", "content": "Grape: Temperature 15°C-35°C. Major diseases: downy mildew (metalaxyl 0.2%), powdery mildew (dinocap 0.1%), anthracnose (carbendazim 0.1%). Proper canopy management critical for disease control. Drip irrigation recommended.", "tags": ["grape", "fruit", "disease", "management"]},

    # Pulses
    {"id": "pulse_001", "content": "Pigeonpea (arhar/toor): Kharif crop, 25°C-35°C. Major pest: pod borer (Helicoverpa) — spray emamectin benzoate 0.5g/L at flowering. Major disease: wilt (Fusarium) — use resistant varieties, seed treatment with Trichoderma 4g/kg.", "tags": ["pigeonpea", "arhar", "pulse", "pest", "disease"]},
    {"id": "pulse_002", "content": "Chickpea (gram): Rabi crop, 15°C-25°C. Major disease: wilt and root rot — seed treatment with carbendazim 2g/kg, use resistant varieties. Major pest: pod borer — spray NPV virus 250 LE/ha. Apply 20:50:20 NPK kg/ha.", "tags": ["chickpea", "gram", "pulse", "disease", "pest"]},
    {"id": "pulse_003", "content": "Black gram (urad): Kharif crop, 25°C-35°C. Diseases: yellow mosaic virus — control whitefly vector, use resistant varieties. Leaf spot: spray mancozeb 0.2%. Rhizobium seed treatment for nitrogen fixation.", "tags": ["black gram", "urad", "pulse", "disease", "management"]},

    # Organic farming
    {"id": "organic_001", "content": "Organic farming principles: No synthetic fertilizers or pesticides. Use FYM, vermicompost, green manure, bio-fertilizers for nutrition. Neem, garlic, chilli extracts for pest control. Requires 3-year transition period for certification.", "tags": ["organic", "farming", "principles", "certification"]},
    {"id": "organic_002", "content": "Neem-based pesticides: Neem seed kernel extract (NSKE) 5% — soak 5kg neem powder in 100L water overnight, filter and spray. Effective against aphids, jassids, caterpillars. Azadirachtin disrupts insect molting and feeding.", "tags": ["organic", "neem", "pesticide", "nske", "botanical"]},
    {"id": "organic_003", "content": "Jeevamrit (liquid organic fertilizer): Mix 10kg cow dung + 10L cow urine + 2kg jaggery + 2kg pulse flour + handful soil in 200L water. Stir daily for 7 days. Apply 200L/acre at 15-day intervals. Provides nutrients + beneficial microbes.", "tags": ["organic", "jeevamrit", "liquid", "fertilizer", "preparation"]},
    {"id": "organic_004", "content": "Panchagavya: Mix 5kg cow dung + 3L cow urine + 2L milk + 2L curd + 1L ghee + 3L tender coconut water + 500g jaggery. Ferment 15 days stirring daily. Dilute 3% in water and spray. Boosts growth and immunity.", "tags": ["organic", "panchagavya", "growth promoter", "preparation"]},

    # Seasonal calendars
    {"id": "season_001", "content": "Kharif season (June-October): Sow rice, maize, cotton, groundnut, pigeonpea, soybean, sugarcane at onset of monsoon. Harvest before November. Pests more severe due to high humidity. Plan fungicide sprays preventively.", "tags": ["season", "kharif", "summer", "monsoon", "calendar"]},
    {"id": "season_002", "content": "Rabi season (October-March): Sow wheat, barley, chickpea, mustard, peas, potato after monsoon. Requires irrigation. Harvest March-April. Lower pest pressure but watch for rust in wheat, pod borer in chickpea.", "tags": ["season", "rabi", "winter", "calendar", "irrigation"]},
    {"id": "season_003", "content": "Zaid/Summer season (April-June): Short duration crops: watermelon, muskmelon, cucumber, fodder. High temperature requires frequent irrigation. Mulching essential for moisture conservation. Watch for thrips and mites.", "tags": ["season", "zaid", "summer", "calendar"]},

    # Soil health indicators
    {"id": "soilhealth_001", "content": "Earthworm count: >10 per square foot indicates healthy soil. 5-10 is moderate. <5 means poor soil health needing organic matter improvement. Earthworms improve aeration, drainage, and nutrient cycling.", "tags": ["soil", "health", "earthworm", "indicator"]},
    {"id": "soilhealth_002", "content": "Water infiltration test: Dig a 30cm hole, fill with water. If drained in <10 min — sandy (low water holding). 10-30 min — loamy (ideal). >30 min — clay (drainage issue). Ideal is 15-25 minutes.", "tags": ["soil", "health", "infiltration", "test"]},
    {"id": "soilhealth_003", "content": "Organic carbon: >0.75% is good, 0.5-0.75% medium, <0.5% low. Every 1% increase in OC improves water holding capacity by 6%. Apply FYM 10t/ha annually to maintain OC levels.", "tags": ["soil", "organic carbon", "test", "management"]},

    # Post-harvest
    {"id": "postharvest_001", "content": "Grain storage: Dry grains to <14% moisture. Store in clean, air-tight containers. Use neem leaves (2% w/w) or alum (1% w/w) as natural grain protectant. Fumigate with aluminum phosphide 3g/ton for insect control.", "tags": ["postharvest", "storage", "grain", "protection"]},
    {"id": "postharvest_002", "content": "Fruit ripening: Use ethylene gas (100-150ppm for 24-48h) or ethephon 0.05% dip for uniform ripening. Never use calcium carbide (carcinogenic — banned in India). Store at 10-15°C for extended shelf life.", "tags": ["postharvest", "ripening", "ethylene", "storage", "safety"]},
    {"id": "postharvest_003", "content": "Vegetable storage: Cool immediately after harvest to remove field heat (hydrocooling or forced air cooling). Store leafy vegetables at 0-2°C with 95% RH, root vegetables at 0-2°C with 90% RH. Tomatoes at 12-15°C.", "tags": ["postharvest", "vegetable", "storage", "cooling"]},
]

ADVISORY_TEMPLATES = {
    "general_advice": "Based on current conditions for {crop} in {location}: {advice}",
    "pest_alert": "PEST ALERT for {crop}: {pest_info}. Monitor your fields closely. {control}",
    "weather_warning": "WEATHER ALERT: {warning}. Recommended action: {action}",
    "fertilizer_rec": "Fertilizer recommendation for {crop}: {recommendation}",
}
